"""
Copy/paste this into whatever file is generated by
    alembic revision -m "Initialize"
to initially create the central DB
"""

def upgrade():
    op.create_table(
        "bot",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(80), unique=True, nullable=False),
        sa.Column("owner", sa.Integer, sa.ForeignKey("user.id"))
    )

    op.create_table(
        "role",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(64), index=True),
        sa.Column("description", sa.String(256))
    )

    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id")),
        sa.Column("role_id", sa.Integer, sa.ForeignKey("role.id"))
    )

    op.create_table(
        "user",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("username", sa.String(64), index=True, unique=True),
        sa.Column("password", sa.String(32)),
        sa.Column("email", sa.String(128), index=True),
        sa.Column("active", sa.Boolean),
        sa.Column("confirmed_at", sa.DateTime),
        sa.Column("provider_id", sa.String(128), index=True, unique=True),
    )

    op.create_table(
        "tickets",
        sa.Column("id", sa.String(36), primary_key=True, index=True),
        sa.Column("who", sa.String(1000), index=True),
        sa.Column("issue", sa.String(1000), index=True),
        sa.Column("details", sa.String(1000), index=True),
        sa.Column("been_read", sa.Boolean, default=False, index=True),
        sa.Column("representative", sa.String(128), default="", index=True)
    )

def downgrade():
    op.drop_table("bot")
    op.drop_table("roles_users")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_table("tickets")
